apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Namespace
    k8s.io/resource: namespaces
    k8s.io/version: v1
  name: core-v1-namespaces
spec:
  resource:
    group: ""
    kind: Namespace
    name: namespaces
    scope: Cluster
    version: v1
