apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: flowcontrol.apiserver.k8s.io
    k8s.io/kind: FlowSchema
    k8s.io/resource: flowschemas
    k8s.io/version: v1beta3
  name: flowcontrol.apiserver.k8s.io-v1beta3-flowschemas
spec:
  resource:
    group: flowcontrol.apiserver.k8s.io
    kind: FlowSchema
    name: flowschemas
    scope: Cluster
    version: v1beta3
