apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: MemcachedVersion
    k8s.io/resource: memcachedversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-memcachedversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: MemcachedVersion
    name: memcachedversions
    scope: Cluster
    version: v1alpha1
