apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: PostgresOpsRequest
    k8s.io/resource: postgresopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-postgresopsrequests
spec:
  resource:
    group: ops.kubedb.com
    kind: PostgresOpsRequest
    name: postgresopsrequests
    scope: Namespaced
    version: v1alpha1
