apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: flowcontrol.apiserver.k8s.io
    k8s.io/kind: PriorityLevelConfiguration
    k8s.io/resource: prioritylevelconfigurations
    k8s.io/version: v1
  name: flowcontrol.apiserver.k8s.io-v1-prioritylevelconfigurations
spec:
  resource:
    group: flowcontrol.apiserver.k8s.io
    kind: PriorityLevelConfiguration
    name: prioritylevelconfigurations
    scope: Cluster
    version: v1
