apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: node.k8s.io
    k8s.io/kind: RuntimeClass
    k8s.io/resource: runtimeclasses
    k8s.io/version: v1
  name: node.k8s.io-v1-runtimeclasses
spec:
  resource:
    group: node.k8s.io
    kind: RuntimeClass
    name: runtimeclasses
    scope: Cluster
    version: v1
