apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: storage.k8s.io
    k8s.io/kind: VolumeAttachment
    k8s.io/resource: volumeattachments
    k8s.io/version: v1
  name: storage.k8s.io-v1-volumeattachments
spec:
  resource:
    group: storage.k8s.io
    kind: VolumeAttachment
    name: volumeattachments
    scope: Cluster
    version: v1
