apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: PersistentVolumeClaim
    k8s.io/resource: persistentvolumeclaims
    k8s.io/version: v1
  name: core-v1-persistentvolumeclaims
spec:
  resource:
    group: ""
    kind: PersistentVolumeClaim
    name: persistentvolumeclaims
    scope: Namespaced
    version: v1
