apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: storage.k8s.io
    k8s.io/kind: CSIDriver
    k8s.io/resource: csidrivers
    k8s.io/version: v1
  name: storage.k8s.io-v1-csidrivers
spec:
  resource:
    group: storage.k8s.io
    kind: CSIDriver
    name: csidrivers
    scope: Cluster
    version: v1
