apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy
    k8s.io/kind: PodDisruptionBudget
    k8s.io/resource: poddisruptionbudgets
    k8s.io/version: v1
  name: policy-v1-poddisruptionbudgets
spec:
  resource:
    group: policy
    kind: PodDisruptionBudget
    name: poddisruptionbudgets
    scope: Namespaced
    version: v1
