apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: LimitRange
    k8s.io/resource: limitranges
    k8s.io/version: v1
  name: core-v1-limitranges
spec:
  resource:
    group: ""
    kind: LimitRange
    name: limitranges
    scope: Namespaced
    version: v1
