apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Node
    k8s.io/resource: nodes
    k8s.io/version: v1
  name: core-v1-nodes
spec:
  resource:
    group: ""
    kind: Node
    name: nodes
    scope: Cluster
    version: v1
