apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: authorization.k8s.io
    k8s.io/kind: LocalSubjectAccessReview
    k8s.io/resource: localsubjectaccessreviews
    k8s.io/version: v1
  name: authorization.k8s.io-v1-localsubjectaccessreviews
spec:
  resource:
    group: authorization.k8s.io
    kind: LocalSubjectAccessReview
    name: localsubjectaccessreviews
    scope: Namespaced
    version: v1
